### ISSUE TITLE
Python install failure

### ISSUE THREAD

**Issue by alexforencich** [nfarring/redisrpc#15]
When I try to install for Python, I get the following error:

```
Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    with open('README.rst','r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
```

Looks like it can't find the README file.  Did this get converted to markdown at some point or is this a different file?

**Comment by nfarring** [comment]
Hi Alex,

I think it is generated during the build process using pandoc. Make sure
you have pandoc installed. redisrpc needs a bit of love; I've been too busy
to maintain it.

Nathan

**Comment by alexforencich** [comment]
Ah, I see.  Make needs to be run on the whole thing before the python component can be installed.  I needed to install pandoc and ruby for that to work.
